/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Controladores.CtrlInterfazPrincipal;
import java.awt.Image;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    private CtrlInterfazPrincipal ctrlInterfazPrincipal;

    /**
     * Creates new form Form
     */
    public InterfazPrincipal() {
        initComponents();

    }

    public void setLblImagen(Image imagen){
        if (imagen != null) {
            ImageIcon icon = new ImageIcon(imagen.getScaledInstance(this.lblImagen.getWidth(), 
                    this.lblImagen.getHeight(), Image.SCALE_SMOOTH));
            this.lblImagen.setIcon(icon);
        }
    }

    ;

    
    public void agregarImagenLabel(Image imagen, JLabel label) {
        ImageIcon icon = new ImageIcon(imagen.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH));
        label.setIcon(icon);
    }

    ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCaras = new javax.swing.JPanel();
        lblImagenEncontrada = new javax.swing.JLabel();
        btnIniciarCaptura = new javax.swing.JButton();
        lblVerificacion = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 800));

        javax.swing.GroupLayout panelCarasLayout = new javax.swing.GroupLayout(panelCaras);
        panelCaras.setLayout(panelCarasLayout);
        panelCarasLayout.setHorizontalGroup(
            panelCarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblImagenEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCarasLayout.setVerticalGroup(
            panelCarasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarasLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(lblImagenEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnIniciarCaptura.setText("Iniciar Captura");
        btnIniciarCaptura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarCapturaActionPerformed(evt);
            }
        });

        lblImagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\gastr\\Documents\\GitHub\\RIV\\imagen.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelCaras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniciarCaptura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelCaras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniciarCaptura)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblVerificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarCapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarCapturaActionPerformed
        this.ctrlInterfazPrincipal.iniciarCaptura();
    }//GEN-LAST:event_btnIniciarCapturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

//    public void agregarCarasPanel(LinkedList<Image> imagenesCarasValidas) {
//        //Remueve los componentes del panel
//        panelCaras.removeAll();
//        panelCaras.repaint();
//
//        JLabel[] labels = new JLabel[imagenesCarasValidas.size()];
//        //Recorre las caras detectadas        
//        for (int i = 0; i < imagenesCarasValidas.size(); i++) {
//            //Obtengo la imagen de la cara
//            Image imagen = imagenesCarasValidas.get(i);
//
//            //Creo el nuevo label
//            JLabel label = new JLabel();
//            //Se hace visible
//            label.setVisible(true);
//            //Lo redimensiono
//            label.setSize(100, 100);
//            //Lo agrego al panel 
//            panelCaras.add(label);
//            panelCaras.validate();
//            //Le agrego la imagen al label
//            agregarImagenLabel(imagen, label);
//            //Lo alinio mas abajo
//            label.setAlignmentY(10 * i);
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarCaptura;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagenEncontrada;
    private javax.swing.JLabel lblVerificacion;
    private javax.swing.JPanel panelCaras;
    // End of variables declaration//GEN-END:variables

    public void setControlador(CtrlInterfazPrincipal ctrlInterfazPrincipal) {
        this.ctrlInterfazPrincipal = ctrlInterfazPrincipal;
    }

    public void setLabelValidacion(String validacion) {
        this.lblVerificacion.setText(validacion);
    }

    public void setLblImagenEncontrada(Image imagen) {
        ImageIcon icon = new ImageIcon(imagen.getScaledInstance(this.lblImagenEncontrada.getWidth(), this.lblImagenEncontrada.getHeight(), Image.SCALE_SMOOTH));
        this.lblImagenEncontrada.setIcon(icon);
    }
}
